global:
  scrape_interval: 5s #scrape every 5s
  evaluation_interval: 5s #evaluate rules every 5s

rule_files:
#  - "one_rule.yml"

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
       - targets: ['127.0.0.1:9090']
   - job_name: 'spring-boot-app'
     metrics_path: '/actuator/prometheus'
     scrape_interval: 5s
     static_configs:
       - targets: ['host.docker.internal:8080']

     basic_auth:
       username: "admin"
       password: "admin"
       